### ISSUE TITLE
Backend modules don't work in version 2.0.0

### ISSUE THREAD

**Issue by rafu1987** [mblaschke/TYPO3-metaseo#233] opened 2016-04-07 13:05 UTC
Since version 2.0.0 the backend modules don't show anything anymore in TYPO3 6.2.19

If I use i.e. the module SEO/metatags on the main page with the globe icon, nothing is shown anymore, but on subpages it shows i.e. the page information for the page selected and subpages.

**Comment by thomaszbz** [comment] 2016-04-07 14:32
Does your main page contain "hidden" pages? Does it contain pages which you cannot access because of permissions?

Please check if your main page is a TYPO3-shortcut-link. If you have such a link, what happens if you change it to a real page?

Also, please make absolutely sure that you have cleared all caches, including "all caches" button and opcode cache in the install tool.

If you still have the problem: Can you send us a screenshot and the response _content_ of the corresponding ajax request(s)? Which http status does it have (press F12/network in your browser)?

**Comment by thomaszbz** [comment] 2016-04-07 15:41
I replaced your ajaxToken with `xxx`. Should not be exposed to the public. Your session is gone anyways.

Please have a look at #225 . #225 was a status 500 error on _some_ pages in the backend like in your case (especially if you have the same hoster). It could be solved by configuration (using FastCGI).

http status 500 means it could still be a bug. To reproduce it, I still need the _content_ of the response. You can get the content (aka source code) of the response with F12 in FF or Chrome.

Please also check if you find an error/exception in your logs (apache/php/typo3 log). If you find some error message, stacktrace and line of code, that would really help.

For the moment, I can't reproduce it yet. metaseo 2.0.0 should run together with TYPO3 6.2.19 (I'm using the same version myself).

**Comment by rafu1987** [comment] 2016-04-07 15:54
**Response headers**
HTTP/1.1 500 Internal Server Error
Date: Thu, 07 Apr 2016 15:51:30 GMT
Server: Apache
Accept-Ranges: bytes
Content-Length: 707
Content-Type: text/html
Connection: keep-alive

The error doesn't seem to be on every hosting environment. i.e. Mittwald has the error and 1&1 doesn't so I think we can rule out a bug of metaseo in this case.

**Comment by thomaszbz** [comment] 2016-04-07 16:02
You've send the headers, not the _content_ of the response. I'd still like to see what it is.

**Comment by rafu1987** [comment] 2016-04-07 16:05
That should be the _content_ you're looking for...
So I'm a bit lost here now - what's the solution for the problem and how come, other backend modules work just fine on the same hosting, etc.

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/css; charset=utf-8" />
		<title>Fehler 500</title>
		<link rel="stylesheet" type="text/css" href="/mittwald_system_pages/css/style.css">   
		
	</head>
	<body>
		<div id="box">
			<div id="oben"></div>
			<div id="textbox">
				<div id="textboxcontent">
					<span class="rad">&nbsp;</span>  
					<h1>Fehler 500</h1>           
					<p>Interner Server Fehler 500</p>
				</div>
			</div>
		<div id="unten"></div>
		</div>
	</body>
</html>
`

**Comment by thomaszbz** [comment] 2016-04-07 16:15
Funny... it got translated :-)

Ok, the error somehow was hidden by Mittwald. That's exactly the same problem we had with jweiland via #225 : How to get an error message? At jweiland we got an error message from the apache logs which was (manually) provided via support ticket.

For the moment, I can say that this exception was _not_ thrown by metaseo's code (but we call a lot of functions from the core which throw 500's). But the error either got obfuscated by Mittwald. Or it's the same issue like in #225 and that would be a configuration error.

The only way to find it out is to get the original error message from the logs (e.g. via sftp or via support ticket). Or you could try to toggle to FastCGI if Mittwald offers that option (In case you don't already use it). FastCGI solved #225 .

**Comment by rafu1987** [comment] 2016-04-08 15:56
I checked on our local server and we have the problem there, too. So I looked at the apache log files there, because Mittwald doesn't provide the Apache logs (only via Support).

We have a Docker environment (I can't tell you much more, I already asked our IT guy :) )

But maybe you can identify the problem with the log entries:

`[Fri Apr 08 15:49:53.755224 2016] [proxy_fcgi:error] [pid 31:tid 140082883249920] [client 10.2.2.23:49231] Premature end of script headers: ajax.php, referer: http://my-site.com/typo3/mod.php?M=web_MetaseoPageseo&moduleToken=xxx&id=1&`

`[Fri Apr 08 15:49:53.755506 2016] [proxy_fcgi:error] [pid 31:tid 140082883249920] [client 10.2.2.23:49231] AH01070: Error parsing script headers, referer: http://my-site.com/typo3/mod.php?M=web_MetaseoPageseo&moduleToken=xxx&id=1&`

`[Fri Apr 08 15:49:53.755656 2016] [proxy_fcgi:error] [pid 31:tid 140082883249920] (22)Invalid argument: [client 10.2.2.23:49231] AH01075: Error dispatching request to : , referer: http://my-site.com/typo3/mod.php?M=web_MetaseoPageseo&moduleToken=xxx&id=1&`

`10.2.2.23 - - [08/Apr/2016:15:49:53 +0000] "POST /typo3/ajax.php?ajaxID=tx_metaseo_controller_ajax_pageseo_metadata%3A%3Aindex&ajaxToken=xxx HTTP/1.1" 500 -`

**Comment by thomaszbz** [comment] 2016-04-08 16:05
`Premature end of script headers: ajax.php` with FCGI used (`proxy_fcgi:error`). This is exactly what I assumed: A duplicate of #225.

Docker is not the reason for this error, I'm using it myself for a [testing environment](https://github.com/thomaszbz/native-dockerfiles-typo3):

I'm quite confident that this error is gone as soon as you don't use CGI or FCGI, in favour of apache_mod_php or FastCGI. If it helps, you might want to let other users know about it in this issue. But it's not a bug in metaseo, therefore I'm closing this issue now.

**Comment by thomaszbz** [comment] 2016-04-08 16:39
To track it down against distro or apache/php: Please check if you have installed the latest updates in your distro. Please check if you use apache 2.4.10 and older. If that is the case, please check if this (patch)[https://bz.apache.org/bugzilla/show_bug.cgi?id=57198] got backported to your distro. If not, you should open a bug and tell them that this got fixed upstream. The affected package is apache or apache's mod_proxy_fcgi or similar. So it seems this is not even an issue of PHP but apache itself.

**Comment by rafu1987** [comment] 2016-04-11 15:30
We use different PHP versions in a container and apache in another container and in fact PHP-FPM in order to use different versions for different projects. In this case it's PHP version 5.6.18, Apache version 2.4.16 and Debian Jessie in the Apache container.

**Comment by rafu1987** [comment] 2016-04-12 14:18
And one other thing. It works on subpages, but not on the main page. Do you know how this can be?

**Comment by thomaszbz** [comment] 2016-04-12 19:29
nope. Just that your setup is very customized and far away from the standard/reference test setup I am using. As you use Apache 2.4.16 (>2.4.10) the patch I posted should already be integrated (hopefully).

I bet this is a bug in one of the componets you are using or config is not right for the purpose you are using it (e.g. check maximum available memory for PHP per request).

There is still a chance that you can track it down so that metaseo has a bug which you can reproduce and tell us what exactly the error is or at least, which piece of code provokes the error.

On the other side: If it works with standard apache/apache_mod_php then it should work on any other platform which claims to be compatible. If you cannot reproduce the error on standard components, then there is no bug in metaseo and your custom setup seems to have a bug (by claiming to be compatible) or there's misconfiguration.

**Comment by rafu1987** [comment] 2016-05-13 14:06
Hello again,

we investigated the problem once again and finally came to a solution - see: http://serverfault.com/questions/711750/apache-2-4-16-response-header-value-clipped

This is the exact problem and could only be fixed by increasing the **HUGE_STRING_LEN** in the source code of the mod_proxy Apache module. Originally, the HUGE_STRING_LEN is limited to 8KB.

Is there any particularly reason, you're sending so much information in your header, instead of the body? Also that explains why it worked on level 1, but not on level 2, because there was too much information in the header on level 1.

For instance, the TYPO3 core module "recycler" also uses ajax calls but in the body, instead of header.

**Comment by thomaszbz** [comment] 2016-05-13 20:34
Thank you for reporting back. Indeed, metaseo 2.0.0 has at least one new http header which we use to identify metaseo ajax requests. This got necessary because we have to use XClasses for a workaround which adresses a limitation in TYPO3. Long story short: We don't overwrite a class via XClasses which is used by other extensions and might lead to non-reproducable errors.

I was not aware that there's a limit for http headers and I also was not aware that we exceeded 8kb. I still don't think this is a bug in metaseo unless an official standard forbids that headers can be longer than 8kb.

As I assumed, this is a configuration issue and now that you solved it for everyone. I'm very happy that there's a solution for #225 now!

I'll think about it at some point, maybe we can save some of the http headers we use.

**Comment by rafu1987** [comment] 2016-05-14 09:30
Thanks for explaining. But **HUGE_STRING_LEN** is not a configuration which can be set in Apache configuration. We had to hack the code of the mod_proxy module to get what we want, so this isn't really a fix for everyone.

Secondly, the headers are so large (X-JSON) that they exceed 8KB easily with a page tree of 10 pages and maybe 2 subpages, because so much information is sent through the headers in the request. Imagine a larger page tree with more subpages and more levels. That explains why it didn't work for me on level 2 but on level 1, because there was just lesser information sent and mod_proxy could handle the request.

Of course this only affects users on development environments or hosting servers which use the mod_proxy module but nevertheless it should be fixed imo because one can't really fiddle with mod_proxy code on shared hostings.

**Comment by thomaszbz** [comment] 2016-05-14 10:59
Thanks for pointing this out. In that case I'd say this is a limitation in the mod_proxy. Have you tried to push your changes upstream? Maybe opened a bug report against mod_proxy?

Now that 8 kb can be easily exceeded via X-JSON's overhead, I don't get why the limitation is at 8 kb and not at ~512 kb or higher. It depends on what the limitation is good for. Of course there might be a reason for a limit (e.g. security), but 8 kb easily breaks applications. Which is not the purpose of a proxy, at least not in general. As long as 8 kb is not a limit which comes from a (http) standard, any proxy who claims to support http should accept requests up to a reasonable number of headers (while "reasonable" should be the "upper" limit).

We don't do something obscure with http headers at metaseo. It was just one additional (and reasonable) header which led to the problem.

**Comment by rafu1987** [comment] 2016-05-17 09:10
Actually not - the limitation is not specifically set in the mod_proxy module but in the httpd configuration - line 303: https://github.com/apache/httpd/blob/50cc09dfef9786d7b732d7a14e4b6ed969f6dece/include/httpd.h

`#define HUGE_STRING_LEN 8192`

It is then used in different Apache proxy modules.

Well, the issue was hard to track down, you're right. But I think there are enough hosting providers relying on Apache with a proxy which makes using metaseo and its backend modules impossible. One example is German TYPO3 Hoster "Mitwald", where the modules don't work either.

I'm sure the additional header was reasonable, but in the end it breaks enough environments to make it hard to work with metaseo modules, where other ajax backend modules work.

**Comment by rafu1987** [comment] 2016-05-19 07:50
Hello again :)
I also found this on stackoverflow with two high rated answers about header limits:

http://stackoverflow.com/questions/686217/maximum-on-http-header-values

Maybe that helps.

**Comment by thomaszbz** [comment] 2016-05-19 10:08
Thanks. In academic terms this is not a bug in metaseo as there is no limit for http headers defined in the http standards (according to your link).

In practical terms, the headers limit (8k) of major web servers will not change soon just because TYPO3/metaseo uses so many headers. Which means that we have to investigate if we can get rid of some of the headers we use.

Could you please send me some debug output of the headers which exceed the 8k limit in your scenario? Maybe there's a lot of headers originating from TYPO3 and other extensions as well. We'll have to investigate what we can do then.

**Comment by rafu1987** [comment] 2016-05-19 10:19
Hey - sure here's an example of the response headers with depth 2 in metaseo backend module:

```
HTTP/1.1 200 OK
Date: Thu, 19 May 2016 10:18:45 GMT
Server: Apache/2.4.20 (Unix)
X-Powered-By: PHP/5.6.20
Expires: 0
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
X-JSON: {"results":21,"rows":[{"uid":"1","pid":"0","t3ver_oid":"0","t3ver_id":"0","t3ver_wsid":"0","t3ver_label":"","t3ver_state":"0","t3ver_stage":"0","t3ver_count":"0","t3ver_tstamp":"0","t3ver_move_id":"0","t3_origuid":"0","tstamp":"1462793209","sorting":"256","deleted":"0","perms_userid":"1","perms_groupid":"2","perms_user":"31","perms_group":"31","perms_everybody":"31","editlock":"0","crdate":"1412796833","cruser_id":"1","hidden":"0","title":"Jean-Luc Haaser - Der Marketing-Guide","doktype":"1","TSconfig":null,"storage_pid":"2","is_siteroot":"1","php_tree_stop":"0","tx_impexp_origuid":"0","url":"","starttime":"0","endtime":"0","urltype":"1","shortcut":"0","shortcut_mode":"0","no_cache":"0","fe_group":"","subtitle":"","layout":"0","url_scheme":"1","target":"","media":"0","lastUpdated":"0","keywords":null,"cache_timeout":"0","cache_tags":"","newUntil":"0","description":"Das ist eine Description","no_search":"0","SYS_LASTCHANGED":"1462873517","abstract":null,"module":"","extendToSubpages":"0","author":"","author_email":"","nav_title":"","nav_hide":"0","content_from_pid":"0","mount_pid":"0","mount_pid_ol":"0","alias":"","l18n_cfg":"0","fe_login_mode":"0","backend_layout":"razor__default","backend_layout_next_level":"razor__sub","tx_realurl_pathsegment":"","tx_realurl_pathoverride":"0","tx_realurl_exclude":"0","tx_realurl_nocache":"0","categories":"0","tx_razor_menulink":"0","tx_metaseo_pagetitle":"","tx_metaseo_pagetitle_rel":"","tx_metaseo_pagetitle_prefix":"","tx_metaseo_pagetitle_suffix":"","tx_metaseo_is_exclude":"0","tx_metaseo_inheritance":"0","tx_metaseo_canonicalurl":"","tx_metaseo_priority":"0","tx_metaseo_change_frequency":"0","tx_metaseo_geo_lat":"","tx_metaseo_geo_long":"","tx_metaseo_geo_place":"","tx_metaseo_geo_region":"","tx_razor_ogimage":"1","_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":"Das ist eine Description","abstract":null,"author":"","author_email":"","lastupdated":null,"pid":"0"},"_depth":1,"lastupdated":""},{"uid":"21","title":"Startseite","doktype":"4","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"1","hidden":"0","starttime":"0","endtime":"0","fe_group":"","module":"","extendToSubpages":"0","nav_hide":"0","_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"1"},"_depth":2},{"uid":"3","title":"Jean-Luc Haaser","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"1","hidden":"0","starttime":"0","endtime":"0","fe_group":"","module":"","extendToSubpages":"0","nav_hide":"0","_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"1"},"_depth":2},{"uid":"27","title":"Bergf\u00fchrer","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"3","hidden":"0","starttime":"0","endtime":"0","fe_group":"0","module":"","extendToSubpages":"0","nav_hide":"0","_CSSCLASS":null,"_SUBCSSCLASS":null,"_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"3"},"_depth":3},{"uid":"28","title":"Mentor","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"3","hidden":"0","starttime":"0","endtime":"0","fe_group":"0","module":"","extendToSubpages":"0","nav_hide":"0","_CSSCLASS":null,"_SUBCSSCLASS":null,"_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"3"},"_depth":3},{"uid":"31","title":"Hinterfrager","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"3","hidden":"0","starttime":"0","endtime":"0","fe_group":"0","module":"","extendToSubpages":"0","nav_hide":"0","_CSSCLASS":null,"_SUBCSSCLASS":null,"_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"3"},"_depth":3},{"uid":"4","title":"Marketing-Exzellenz","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"1","hidden":"0","starttime":"0","endtime":"0","fe_group":"","module":"","extendToSubpages":"0","nav_hide":"0","_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"1"},"_depth":2},{"uid":"29","title":"Unterseite 1","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"4","hidden":"0","starttime":"0","endtime":"0","fe_group":"0","module":"","extendToSubpages":"0","nav_hide":"0","_CSSCLASS":null,"_SUBCSSCLASS":null,"_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"4"},"_depth":3},{"uid":"30","title":"Unterseite 2","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"4","hidden":"0","starttime":"0","endtime":"0","fe_group":"0","module":"","extendToSubpages":"0","nav_hide":"0","_CSSCLASS":null,"_SUBCSSCLASS":null,"_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"4"},"_depth":3},{"uid":"22","title":"Themenfelder","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"1","hidden":"0","starttime":"0","endtime":"0","fe_group":"0","module":"","extendToSubpages":"0","nav_hide":"0","_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"1"},"_depth":2},{"uid":"23","title":"Kundenstimmen","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"1","hidden":"0","starttime":"0","endtime":"0","fe_group":"0","module":"","extendToSubpages":"0","nav_hide":"0","_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"1"},"_depth":2},{"uid":"24","title":"Download","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"1","hidden":"0","starttime":"0","endtime":"0","fe_group":"0","module":"","extendToSubpages":"0","nav_hide":"0","_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"1"},"_depth":2},{"uid":"15","title":"Blog","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"1","hidden":"0","starttime":"0","endtime":"0","fe_group":"","module":"","extendToSubpages":"0","nav_hide":"0","_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"1"},"_depth":2},{"uid":"10","title":"Kontakt","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"1","hidden":"0","starttime":"0","endtime":"0","fe_group":"","module":"","extendToSubpages":"0","nav_hide":"0","_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"1"},"_depth":2},{"uid":"12","title":"Vielen Dank f\u00fcr Ihre Kontaktanfrage","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"10","hidden":"0","starttime":"0","endtime":"0","fe_group":"","module":"","extendToSubpages":"0","nav_hide":"1","_CSSCLASS":null,"_SUBCSSCLASS":null,"_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"10"},"_depth":3},{"uid":"17","title":"Footer Men\u00fc","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"1","hidden":"0","starttime":"0","endtime":"0","fe_group":"","module":"","extendToSubpages":"0","nav_hide":"1","_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"1"},"_depth":2},{"uid":"19","title":"Impressum","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"17","hidden":"0","starttime":"0","endtime":"0","fe_group":"0","module":"","extendToSubpages":"0","nav_hide":"0","_CSSCLASS":null,"_SUBCSSCLASS":null,"_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"17"},"_depth":3},{"uid":"20","title":"Datenschutz","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"17","hidden":"0","starttime":"0","endtime":"0","fe_group":"0","module":"","extendToSubpages":"0","nav_hide":"0","_CSSCLASS":null,"_SUBCSSCLASS":null,"_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"17"},"_depth":3},{"uid":"6","title":"Nicht im Men\u00fc","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"1","hidden":"0","starttime":"0","endtime":"0","fe_group":"","module":"","extendToSubpages":"0","nav_hide":"1","_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"1"},"_depth":2},{"uid":"13","title":"Suche","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"6","hidden":"0","starttime":"0","endtime":"0","fe_group":"0","module":"","extendToSubpages":"0","nav_hide":"1","_CSSCLASS":null,"_SUBCSSCLASS":null,"_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"6"},"_depth":3},{"uid":"8","title":"404","doktype":"1","mount_pid":"0","php_tree_stop":"0","t3ver_id":"0","t3ver_state":"0","keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"","pid":"6","hidden":"0","starttime":"0","endtime":"0","fe_group":"","module":"","extendToSubpages":"0","nav_hide":"1","_CSSCLASS":null,"_SUBCSSCLASS":null,"_overlay":{"keywords":0,"description":0,"abstract":0,"author":0,"author_email":0,"lastupdated":0,"pid":0},"_base":{"keywords":null,"description":null,"abstract":null,"author":"","author_email":"","lastupdated":"0","pid":"6"},"_depth":3}]}
Last-Modified: Thu, 19 May 2016 10:18:45 GMT
Vary: Accept-Encoding
Content-Encoding: gzip
Connection: keep-alive, Keep-Alive
X-UA-Compatible: IE=edge
X-Content-Type-Options: nosniff
Content-Length: 1291
Keep-Alive: timeout=5, max=97
Content-Type: application/json; charset=utf-8
```

**Comment by pcvolkmer** [comment] 2016-05-19 13:30
What is the purpose of repeating response body in a custom response header "X-JSON"?

**Comment by thomaszbz** [comment] 2016-05-19 14:31
A X-JSON http header for regular data does not make sense to me either. To my knowledge, this has also not changed in metaseo 2.0.0. But I will definitely investigate on this. I'll have to reproduce it first.

**Comment by pcvolkmer** [comment] 2016-05-27 19:37
I have done some research and guess the issue is related to https://forge.typo3.org/issues/50509. Please note the related [changeset](https://forge.typo3.org/projects/typo3cms-core/repository/revisions/3124ebb4df25fa3712faa51e1624a2e96c38fe8e/diff/typo3/sysext/core/Classes/Http/AjaxRequestHandler.php).

I have compared this changeset with the Typo3 version[ 6.2.19](https://forge.typo3.org/projects/typo3cms-core/repository/entry/typo3/sysext/core/Classes/Http/AjaxRequestHandler.php?rev=6.2.19#L249) as described by @rafu1987 in the issue description.

If you take a look at it, you will find out, that the issue cause starts by calling `AbstractPageSeoController#indexAction()`, last line: `$ajaxObj->redner()`. In Typo3 version 6.2.19 `AjaxRequestHandler#render()` and further on [`AjaxRequestHandler#renderAsJSON()`](https://forge.typo3.org/projects/typo3cms-core/repository/entry/typo3/sysext/core/Classes/Http/AjaxRequestHandler.php?rev=6.2.19#L249) is called without recognition of any difference in 'json', 'jsonhead' or 'jsonbody'. `AjaxRequestHandler#renderAsJSON()` only uses header in Typo3 version 6.2.19.

**Comment by thomaszbz** [comment] 2016-05-27 19:49
@pcvolkmer Thanks for the hint. That brings us much closer to a patch.

**Comment by pcvolkmer** [comment] 2016-05-27 20:04
I have prepared #240 and within my tiny local testing environment without proper data it sends response via HTTP body not within X-JSON header any more.
I would prefer @rafu1987 should also take a look at it if it fixes his issue for his larger environment.

**Comment by thomaszbz** [comment] 2016-05-27 20:39
Yes, would be great if @rafu1987 could test your change in his full-blown hosting setup.

It looks as if forge #50509 never made it into 6.2.x

    git branch
    * (losgelöst von TYPO3_6-2-25)
    git log |grep 50509
    <empty>

    git checkout TYPO3_7-6-9
    HEAD ist jetzt bei ecc5525... [RELEASE] Release of TYPO3 7.6.9
    git log |grep 50509
    Resolves: #50509 <-- from commit message

**Comment by thomaszbz** [comment] 2016-05-27 20:52
Reproduced that json data is in the http header, using 6.2.25 and ``const CONTENT_FORMAT_JSON = 'json';``:

    X-JSON: {"results":12,"rows":[{"uid":"67","pid":"2","t3ver_oid":"
    [...]
    ","author":"","author_email":"","lastupdated":"0","pid":"67"},"_depth":2}]}

That can easily exceed a limit of 8kb for the http headers section.

Any version of 6.2.x should be affected together with metaseo 2.0.0 (at least) as long as the web server or a proxy limits the size of a http header section.

I did not investigate if 1.0.x releases of metaseo are affected. As said, we use some "newer" infrastructure of the 6.2 release in terms of ajax. Maybe TYPO3's #50509 bug had no effect on 1.0.x releases of metaseo. At least we were not aware of this issue before 2.0.0.

**Comment by rafu1987** [comment] 2016-05-27 21:21
Thanks for all the information! I will test it on monday in our local environment and some hosting environments, where the error occured, too.

As of metaseo 1.0.x: We used that version on the same local environment as we do now and did not encounter any problems.

**Comment by thomaszbz** [comment] 2016-05-27 22:15
#50509 should have been classified as a bug, as common hosting environments were broken by the ~8kb limit. If it had been a bug, there would also have been a chance that the patch had been backported. Now that #50509 was classified as a feature, there was no formal "need" for a backport to 6.2.x.

https://forge.typo3.org/issues/76340 tries to heal that. Anyhow, I'd still apply 958bce9 because we never know if, when and how #76340 is solved. Plus, don't I understand the concept of X-JSON data in a http header at all. We'll never need that at least for metaseo.

**Comment by thomaszbz** [comment] 2016-05-28 12:49
76340 will not make it to a code change in 6.2.x core (according to https://forge.typo3.org/issues/76340 ).

**Comment by thomaszbz** [comment] 2016-05-28 19:08
@pcvolkmer please add yourself to the list of contributors at https://github.com/mblaschke/TYPO3-metaseo/blob/develop/Documentation/Introduction/Index.rst

**Comment by rafu1987** [comment] 2016-05-30 07:54
@thomaszbz @pcvolkmer We tested #958bce9 on our local setup and with the change to `jsonbody` it works perfectly! Thanks to all! :)

**Comment by thomaszbz** [comment] 2016-05-30 09:27
Great. I'll merge 958bce9 asap. A new bug fix release is already scheduled, together with @mblaschke . 

Thanks to @pcvolkmer @rafu1987 for all the investigation and the patch. We'd appreciate your help during the ongoing development of metaseo. We're also on [slack](https://typo3.slack.com/messages/ext-metaseo/), if you want to contact us quickly.

**Comment by thomaszbz** [comment] 2016-05-30 22:32
Added @pcvolkmer to the list of contributors via 1465743f659e1fab72628aaf7f80b82fc13fcb8d.

**Closed** 2016-05-30 22:34 UTC
Labels: bug, need: feedback, patch available

**Comment by rafu1987** [comment] 2016-09-14 08:23
Hello,

@thomaszbz: When is the bugfix and version 2.0.1 of metaseo gonna make it to the TER?

**Comment by thomaszbz** [comment] 2016-09-14 08:29
This week, if @mblaschke finds the time to release it.

**Comment by rafu1987** [comment] 2016-09-14 08:33
Awesome! :thumbsup:
