### ISSUE TITLE
No Typoscript template found! error with cronjob task „Sitemap.xml builder“

### ISSUE THREAD

**Issue by kjeldschumacher** [mblaschke/TYPO3-metaseo#226] opened 2016-03-12 18:25 UTC
With TYPO3 7.6.4, 2.0.0 metaseo and composer mode using the cronjob task „Sitemap.xml builder“ I am getting the error `No Typoscript template found`.

I checked it twice that the static template is included. Looking at the include settings and template analyzer.

**Comment by thomaszbz** [comment] 2016-03-12 23:27
Tried to reproduce this with TYPO3 7.6.4, metaseo 2.0.0, realurl installed:

For me, running "Sitemap.xml builder" task manually was successful and created a [sitemap](https://docs.typo3.org/typo3cms/extensions/metaseo/AdministratorManual/Index.html#scheduler-tasks):

    typo3/uploads/tx_metaseo/sitemap_xml# ls -lh
    total 8.0K
    -rw-r--r-- 1 www-data www-data 225 Mar 12 23:20 index-r1.xml.gz
    -rw-r--r-- 1 www-data www-data 316 Mar 12 23:20 sitemap-r1-p0.xml.gz

Where excactly can you see the error `No Typoscript template found`?

**Comment by thomaszbz** [comment] 2016-03-14 21:27
@kjeldschumacher Could you solve it?

**Comment by kjeldschumacher** [comment] 2016-03-15 10:17
Hey, no still the same error. Will try to find the time during my holiday to debug it further.

**Comment by thomaszbz** [comment] 2016-03-22 07:33
Do you get the same error if you disable metaseo in the extension manager?

For the moment, it looks like a configuration issue. Please have a look at http://mjnext.com/blog/2012/07/16/typo3-no-typoscript-template-found/ and similar pages. You'll find a lot about it.

Besides TypoScript configuration, please also make sure that a root page is properly set in page properties.

**Comment by thomaszbz** [comment] 2016-05-30 11:53
@kjeldschumacher what happens if you disable metaseo-extension temporarily via extension manager?

**Comment by albert-spangler** [comment] 2016-06-20 08:10
i have the same problem:
"Die Ausführung von Task "Sitemap.xml builder (metaseo)" ist fehlgeschlagen mit folgender Meldung: No TypoScript template found!"

**Comment by thomaszbz** [comment] 2016-06-20 09:23
@albert-spangler Which versions of metaseo, TYPO3 and PHP are you using?

**Comment by albert-spangler** [comment] 2016-06-20 11:11
typo3 7.6.3
metaseo 2.0.0 beta 	
PHP 5.5.9

**Comment by thomaszbz** [comment] 2016-06-20 11:25
Great. Your versions should work according to the tests I made. Did you upgrade metaseo or TYPO3 recently?

Please make sure that you clear all caches after the upgrade multiple times in different order. Please include cache and opcode in TYPO3's upgrade tool as well as the orange system cache button which can be enabled via the install tool. Please make sure that you play around with clearing caches multiple times. I experienced that this really can help sometimes.

Do you have an opcode/PHP cache enabled on your system? Are multiple of these caches enabled/installed (e.g. xcache _and_ apc)? What does the install tool report about PHP caches?

Please report back if one of the steps helped. If not, we need to further track it down. I'd also like to hear from @kjeldschumacher if he got this problem solved somehow.

**Comment by thomaszbz** [comment] 2016-07-09 08:42
@albert-spangler Is this still an issue?

**Comment by thomaszbz** [comment] 2016-12-09 15:44
@kjeldschumacher @albert-spangler Does this still happen with recent versions of MetaSEO and TYPO3?

Please try with MetaSEO 2.0.1+ and TYPO3 7.6.11+

**Comment by thomaszbz** [comment] 2016-12-11 10:58
Seems to be an old phenomenon: https://forge.typo3.org/issues/53074

That said, I'm pretty sure that this issue is about configuration. Please make sure that you have statically included metaseo's template:

![auswahl_075](https://cloud.githubusercontent.com/assets/11200727/21079666/0e0383ca-bf99-11e6-9d4c-84b29779a228.png)

That's documented and there also is a nice tutorial [video](https://jweiland.net/video-anleitungen/typo3/interessante-typo3-extensions/metaseo.html).

**Comment by thomaszbz** [comment] 2016-12-11 12:26
Also tried a fresh install in composer mode with

```
cat composer.json 
{
  "repositories": [
    { "type": "composer", "url": "https://composer.typo3.org/" }
  ],
  "name": "my-vendor/my-typo3",
  "require": {
    "typo3/cms": "^7.6",
    "typo3-ter/metaseo": "^2.0"
  },
  "extra": {
    "typo3/cms": {
      "cms-package-dir": "{$vendor-dir}/typo3/cms",
      "web-dir": "web"
    }
  }
}
```

After that, I created a page, added metaseo's static template and ran the task to create the xml sitemap. Everything worked great (PHP 5.6, TYPO3 7.6.14 in composer mode, metaseo 2.0.1):

    /var/www/typo3_composer/web/uploads/tx_metaseo/sitemap_xml# ls -l
    -rw-r--r-- 1 www-data www-data 228 Dec 11 12:19 index-r1.xml.gz
    -rw-r--r-- 1 www-data www-data 248 Dec 11 12:19 sitemap-r1-p0.xml.gz

For testing, I used this [docker file for TYPO3](https://github.com/thomaszbz/native-dockerfiles-typo3), just with composer mode enabled.

Now that everything works, I'm closing this issue.

**Closed by thomaszbz** 2016-12-11 12:26 UTC
Labels: bug reported, need: feedback
