### ISSUE TITLE
Info icon under URL and Pagetitle submodule does not work

### ISSUE THREAD

**Issue by mediaessenz** [mblaschke/TYPO3-metaseo#438] opened 2017-04-15 15:03 UTC
**MetaSEO version**: 3.0.0-dev

**TYPO3 version**: 8.7.0

**PHP version**: 7.0.0

**Comment by thomaszbz** [comment] 2017-04-15 22:53
_Not_ reproduced with 

MetaSEO version: 3.0.0-dev, d8cfe470c8c6bf3e1d4c00aa9404dd88c50fc927
TYPO3 version: 8.7.1-dev, 6da38a68794a35d3a2fb9093d083bcaeaf1b35e2
PHP version: 7.0.16

I get a flash message, showing the URL.

@mediaessenz of course, you may not click the `i` directly but the area around the `i`. Watch your mouse pointer change and there you have it. That's pretty self-explaining :-)

No it's not. It's pretty much the same issue as in #394, just that the clickable area is _very_ small. Could easily happen that you fixed that already.

**Comment by thomaszbz** [comment] 2017-04-15 23:10
Reproduced it against

MetaSEO version: 3.0.0-dev, your branch dev/394-show-icons-only-on-hover, 8e8ad8feac23d74070d835a72a938602cf58fcf4
TYPO3 version: 8.7.1-dev, latest master, 6da38a68794a35d3a2fb9093d083bcaeaf1b35e2
PHP version: 7.0.16

The `i` looks a bit bigger, and there is no clickable area left at all. Still, it's the same issue. Totally CSS selector related.

**Comment by thomaszbz** [comment] 2017-04-15 23:18
Via #394 (8e8ad8f), the hover effect works, but _all_ icons still are not clickable directly, not only the info icon (`i`). I assume that bringing back clickability for _all_ icons also brings it back for the info icon (`i`).

**Comment by thomaszbz** [comment] 2017-04-15 23:38
I reported back in #394. I think this issue is a duplicate of #394. I'll leave this issue open for some time until things get sorted out.

**Comment by thomaszbz** [comment] 2017-04-17 02:30
Things sorted out. And yes, it's a duplicate of #394.

**Closed by thomaszbz** 2017-04-17 02:30 UTC
Labels: duplicate
