### ISSUE TITLE
Place Google Code in <head>

### ISSUE THREAD

**Issue by npostnik** [mblaschke/TYPO3-metaseo#496] opened 2017-07-04 12:12 UTC
**MetaSEO version**: 2.1.0
**TYPO3 version**: 7.6.18

Hi, Google insists that the tracking code is placed inside the `<head>`-tag of the page. Otherwise the site cannot be verified. Is is possible to place the Google tracking code in `<head>` and/or add a configuration option for this?

Kind regards, Natalia

**Comment by thomaszbz** [comment] 2017-07-04 12:49
@npostnik Thanks for pointing this out.

Putting the tracking code into the header is a duplicate of #123.

@npostnik What are the implications of not doing so? Is there a source to it?

Years ago, it seemed to be best practise to not put it into the header section (as discussed here: https://stackoverflow.com/questions/3694356/is-there-a-reason-to-put-google-analytics-in-head-and-not-in-body and here: https://github.com/wvuweb/cleanslate-cms/issues/164).

Please make sure that you don't mismatch google verification code (which MetaSEO _does_ place into the `<head>` section) and the javascript code of GA.

**Comment by thomaszbz** [comment] 2017-07-05 19:44
Still missing feedback. Please report back in #123. Closing this issue.

**Closed as completed by thomaszbz** 2017-07-05 19:44 UTC
Labels: duplicate
