### ISSUE TITLE
Shortcuts generate "PHP Warning: ksort() expects parameter 1 to be array, null given in [...]"

### ISSUE THREAD

**Issue by kathangeorg** [mblaschke/TYPO3-metaseo#23] opened 2015-03-09 09:22 UTC
Pages with a Shortcut generate the following PHP Warning in metaseo 1.0.5 and 1.0.6:

    PHP Warning: ksort() expects parameter 1 to be array, null given in   [...]typo3conf/ext/metaseo/Classes/Utility/GeneralUtility.php line 173

We use the following TYPO3 configuration:

    // Development
    $GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = '1';
    $GLOBALS['TYPO3_CONF_VARS']['FE']['debug'] = '1';
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['devIPmask'] = '*';
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['displayErrors'] = '1';
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['enableDeprecationLog'] = 'file';
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['sqlDebug'] = '1';
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['systemLogLevel'] = '0';
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['exceptionalErrors'] = '28674';
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['clearCacheSystem'] = '1';
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['debug'] = '1';

**Comment by mblaschke** [comment] 2015-03-18 21:26
Fixed in master
Duplicate of #29

**Closed by mblaschke** 2015-03-18 21:26 UTC
Labels: duplicate
