### ISSUE TITLE
missing home url in sitemap.xml

### ISSUE THREAD

**Issue by derBoogie** [mblaschke/TYPO3-metaseo#190] opened 2016-01-12 12:21 UTC
My sitemap.xml doesn't contain a home url.
My home page is the root page (uid 1) and all other pages are subpages of the home page.
Is It possible to render the home url within the sitemap.xml, in my case?

**Comment by mblaschke** [comment] 2016-01-12 12:28
Is the root page a page (not a shortcut pointing to a home url)?

**Comment by derBoogie** [comment] 2016-01-12 14:17
Hi,
the root page is a standard page, not a shortcut, see:

![pagetree](https://cloud.githubusercontent.com/assets/1611217/12265793/945201f6-b93f-11e5-8993-a9dfd885775b.jpg)

greetings TJ

**Comment by mblaschke** [comment] 2016-01-13 21:19
Currently it's a common issue because some caching checks are failing if root page is not a shortcut.

Workaround: move content to a "home" page and set root page to shortcut :(

**Comment by thomaszbz** [comment] 2016-01-26 17:19
@mblaschke I have a similar setup as derBoogie: My home page also is not a shortcut (because shortcut can lead to duplicate content and unnecessary 301). Still, the home page is indexed correctly via MetaSEO (currently at 472621b3e63aa09c0fd573eece95c64c53c28a49).

@derBoogie Which version of MetaSEO and which version of TYPO3 CMS have you been testing with?

**Comment by dsteinborn** [comment] 2016-09-06 14:08
Run into the same problem and found the reason. `config.absRefPrefix` is set to `/` then in `processLinkUrl` of `SitemapIndexHook.php` absRefPrefix is removed from `$linkUrl`. The Link for the home page is now empty and will not pass `GeneralUtility::checkUrlForBlacklisting`.

Temporary solution is to enable "TypoLink indexer" and add a TypoLink to the home page with `forceAbsoluteUrl = 1`.

**Comment by thomaszbz** [comment] 2016-09-06 14:25
@dsteinborn Which is your metaseo and TYPO3 version?

**Comment by dsteinborn** [comment] 2016-09-06 17:49
@thomaszbz TYPO3 7.6.10 and Metaseo 2.0.0 beta

**Comment by thomaszbz** [comment] 2016-12-10 11:18
Workaround: I don't use `absRefPrefix`, but together with RealURL, I use

```
#RealUrl BASEURL
BASEURL = http://www.example.com/

#https
[globalString = _SERVER|HTTPS=on]
    BASEURL = https://www.example.com/
[global]

```

... together with a

`<base href="https://www.example.com/">`

... in the template.

I am aware that not everybody likes to use base URLs (it's somehow hard coded). All I can say is that it works at least. We should fix this as long as `absRefPrefix` is widely used. Which it might be.

**Comment by thomaszbz** [comment] 2016-12-10 12:36
I could not reproduce this issue with RealUrl disabled: A requested page `http://www.example.com` made it into metaseo's index.

However, I could reproduce this issue with RealUrl enabled (RealUrl 2.1.5, TYPO3 7.6.14): A requested page `www.example.com` did _not_ make it into metaseo's index.

@dsteinborn Could you please try to tweak RealUrl the way I did for #224 ? Does that fix your issue? Please also use the latest version of RealUrl (btw: Did you use RealUrl and if, which version did you use?)

In respect to root pages, we sometimes get [strange URLs](https://github.com/dmitryd/typo3-realurl/issues/350) from RealURL via the hook. RealUrl's bug tracker is for "_confirmed_ bugs" only, so maybe you want to confirm it ;-)

**Comment by thomaszbz** [comment] 2016-12-10 13:38
I think we should consider the `/` we get for rather like a suffix than like a prefix. That would also make sense in respect to storage of urls in `tx_metaseo_sitemap`:

```
select page_url from tx_metaseo_sitemap;
+----------+
| page_url |
+----------+
| code/    |
| /        |
+----------+
```

**Comment by thomaszbz** [comment] 2016-12-10 14:39
@dsteinborn @derBoogie Thanks for catching this. Should be fixed now.
Please try out 236d6cd1580f1ed0a1f48129831a7e2302b64a6f via the latest develop branch and report back if the issue is fixed now.

**Closed** 2016-12-10 14:40 UTC
Labels: bug, patch available
