### ISSUE TITLE
Is there any timetable for compatibility with the now released Typo3 v8 LTS?

### ISSUE THREAD

**Issue by al-Iskandar** [mblaschke/TYPO3-metaseo#376] opened 2017-04-08 08:24 UTC

**Comment by thomaszbz** [comment] 2017-04-08 14:49
The plan is:

- Wait for 8 LTS to get released (which is the case now)
- After that: Analyse necessary changes and start working to get MetaSEO 3.0.0 compatible to 8 LTS

MetaSEO is a community-driven project. How long it takes depends on how fast issues get reported and patches are contributed. To my knowledge, we don't have a major sponsor, letting us work full-time on the project.

@mediaessenz is already working hard on an alternative for our ExtJS 3.4.1.1 Javascript code, which is supposed to be discontinued by the 8 LTS core release. That alone would already be a major step towards 8 LTS compatibility.

I would expect that it takes several months from now on, depending on what needs to be done. Of course, users can speed up the whole process by sponsoring/funding things.

**Comment by thomaszbz** [comment] 2017-04-08 22:02
**Update**: It looks as if 8LTS still comes shipped with ExtJS, thanks to the everlasting PageTree :wink:.

With some luck, MetaSEO 3.0.0 can become compatible with 8LTS without having to port all the Javascript. There's still a lot of things to do, but if we can port the Javascript _after_ releasing 3.0.0, 8LTS-compatibility is much sooner on the horizon. We're still investigating what needs to be done, now that 8LTS is finally released. Any help is appreciated.

Once again, I'm _very_ happy with the decision to wait for the final LTS8.

**Comment by thomaszbz** [comment] 2017-04-09 01:16
**Update**: Tracking `8LTS: must-have`-tagged and other solved issues in [milestone 3.0.0](https://github.com/mblaschke/TYPO3-metaseo/milestone/6), whereas optional (`8LTS: whishlist`-tagged) steps are now tracked in [milestone 3.1.0](https://github.com/mblaschke/TYPO3-metaseo/milestone/18).

@al-Iskandar Hope that helps users to figure out how far LTS8-compatibility has become.

**Comment by thomaszbz** [comment] 2017-04-09 13:16
**Update:** A new branch with name `feature/8lts` is available. It is still unstable, but some features already seem to run. Even our Javascript code already (still) runs. You can help us: Test with the new branch, report bugs & fix issues.

**Comment by thomaszbz** [comment] 2017-04-10 04:22
**Update:** Indexing and generating sitemaps still seems to work in principle.

**Comment by thomaszbz** [comment] 2017-04-14 04:42
**Update:** Besides #411, everything seems to work already. Issues from #411 can be mitigated by installing the compatibility7 extension.

The remaining issues are design related, thereby not blocking any feature.

**Comment by thomaszbz** [comment] 2017-04-14 18:44
**Update:** TCA checks performed via install tool go green now.

**Comment by thomaszbz** [comment] 2017-04-14 21:18
**Update:** @mediaessenz and @simonschaufi fixed icon related stuff.

**Comment by thomaszbz** [comment] 2017-04-15 03:45
**Update:** MetaSEO's test suite now goes green again. Running the test suite against TYPO3's new testing framework now is documented.

**Comment by thomaszbz** [comment] 2017-04-17 03:44
**Update:** Grids look great now and all the grid icons should be clickable again.

**Comment by thomaszbz** [comment] 2017-04-17 11:00
#411 is solved, dealing with the removed url_scheme. Read it for details.

**Comment by thomaszbz** [comment] 2017-04-17 11:01
All issues in milestone 3.0.0 are currently solved. Special thanks go to @mediaessenz who helped a lot.

**Comment by RKlingler** [comment] 2017-06-02 09:49
Hi, I need to update a client's site to Typo3 8 soon and they are relying on metaseo heavily.
Can you give me an update on what's the current status of version 3? And can you already give an updated estimation of when you will be able to release a stable version?

**Comment by thomaszbz** [comment] 2017-06-02 10:22
@RKlingler Since end of April, bug reports against branch feature/8lts were very rare. In the meantime, packagist reports more than 100 downloads of 3.0.0-dev. So there should have been some testing going on in the meantime.

Until 3.0.0 is released, I suggest to take feature/8lts via composer or by manually cloning that branch (non-composer-mode). For Typo3 8 LTS, I'm not aware of any regression since 7.6/metaseo 2.0.4. I've also heard of users using it in production already.

Should be safe to release it soon. Which we will do.

**Comment by RKlingler** [comment] 2017-06-02 14:41
Thanks for your response. I'ts much appreciated.
Since the Typo3 dependency in version 2 is set to 6.2.1 - 7.6.99 I assumed I wouldn't be able to use it in production on Typo3 8. But it's good to hear that I have these options. I'm sure one of them will work.

Thanks again, and also thank you for the work you do in maintaining this extension.

**Comment by thomaszbz** [comment] 2017-06-02 14:44
Version 2.0.x is known to _not_ work in TYPO3 8 LTS.

**Comment by thomaszbz** [comment] 2017-06-10 21:30
Merged new features from 2.1.0 into 3.0.0. Current state seems to be ready to be released now.

**Comment by thomaszbz** [comment] 2017-06-11 22:03
MetaSEO 2.1.0 and 3.0.0 are released now.

**Closed by thomaszbz** 2017-06-11 22:03 UTC
Labels: suggestion/question
