### ISSUE TITLE
Minor rendering bug in Sitemap backend Module (pagination)

### ISSUE THREAD

**Issue by PanadeEdu** [mblaschke/TYPO3-metaseo#237] opened 2016-04-15 09:44 UTC
Assume you have 2 pages of entries in the Sitemap Backend Module.
You go to page two, mark all entries and hit delete.
The pagination then seems to think you are on the wrong page. 

However I havent seen any negative effects except for the displayed numbers.

**Comment by thomaszbz** [comment] 2016-04-15 10:51
Which versions of metaseo, TYPO3 and PHP are you using?

**Comment by PanadeEdu** [comment] 2016-04-15 11:52
TYPO3 6.2 
PHP 5.5.9
Metaseo 2.0

**Comment by thomaszbz** [comment] 2016-07-09 09:22
Trying to reproduce with metaseo 2.0.0, TYPO3 7.6.10-dev, PHP 5.6.

I used 10 entries for the page size: `MetaSeo.sitemap.conf.pagingSize = 10`.

Steps to reproduce:

![auswahl_010](https://cloud.githubusercontent.com/assets/11200727/16707222/31026ebe-45c7-11e6-9d7a-ec19895fd191.png)
![auswahl_011](https://cloud.githubusercontent.com/assets/11200727/16707220/30ffdf6e-45c7-11e6-9659-642fcddd0e9b.png)

Result:
![auswahl_012](https://cloud.githubusercontent.com/assets/11200727/16707223/31050854-45c7-11e6-817c-4426e253737f.png)

Expected result (left this section and reentered the sitemap section):
![auswahl_013](https://cloud.githubusercontent.com/assets/11200727/16707221/3101f2ea-45c7-11e6-87d4-0ea163fec17e.png)

So far I can't find a bug here. Will try what happens when the last page is deleted.

**Comment by thomaszbz** [comment] 2016-07-09 09:33
This time the _last_ page is deleted.

Trying to reproduce with metaseo 2.0.0, TYPO3 7.6.10-dev, PHP 5.6.

I used 10 entries for the page size: `MetaSeo.sitemap.conf.pagingSize = 10`.

# Steps to reproduce:
![auswahl_014](https://cloud.githubusercontent.com/assets/11200727/16707279/9855b8c2-45c8-11e6-84e2-d2eda5d4d379.png)
![auswahl_015](https://cloud.githubusercontent.com/assets/11200727/16707280/985a580a-45c8-11e6-8426-62ac6955fc31.png)

# Result:
![auswahl_016](https://cloud.githubusercontent.com/assets/11200727/16707281/985e4e1a-45c8-11e6-9f1d-a6f8028c0c84.png)

# Expected result (left this section and reentered the sitemap section):
This would be expected _only_ if we display the _new_ last page because we deleted the _old_ one. In that case this is a bug. However, when deleting a page somewhere in the middle, we should stick to that page number because then the user can delete page by page without having to switch to the next page.

![auswahl_017](https://cloud.githubusercontent.com/assets/11200727/16707282/9861e372-45c8-11e6-88b0-21ac301a191b.png)

**Comment by thomaszbz** [comment] 2016-07-09 09:52
It's a rendering bug in the sense that `Page 3 of 2` looks strange. On the other hand this is consistent with staying on the same page when the deletion happens somewhere in the middle.

I think it is dangerous to let the user think that he or she always deletes the _next_ page until the last page comes and suddenly the user could be tricked into deleting the _previous_ page unwllingly.

Therefore, I think the benefit for mitigating the strange rendering like `Page 3 of 2` is eaten up by the lack of consistency. I'd say this is a won't fix.

**Closed** 2016-07-09 09:54 UTC
Labels: bug, wontfix
