### ISSUE TITLE
cleanup: search engine should get a complete and consistent sitemap ANY TIME.

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#26] opened 2015-03-09 12:46 UTC
How to reproduce:
- After running garbage collection task, the sitmap is empty
- After running sitemap.xml builder task, the sitmap is still empty
- After clicking around on the page, the sitemap gets filled over the time. In the meantime, it is not consistent to the actual content of a web page.

Suggested enhancement:
- There should be an automated way to clean up the sitemap leaving it in a filled state including ALL pages without clicking around manually.

Therefore
- garbage collection task should execute the sitemap.xml builder task
- sitemap.xml builder task should fill the sitemap with ALL pages

Result of the suggested enhancement: Cleanup and creation of sitemap.xml can be automated by running garbage collection and (optionally) sitemap.xml builder via TYPO3 scheduler.

Tested on pre-2.0.0 ( 598e3f6 )

**Comment by thomaszbz** [comment] 2015-03-09 21:58
hook_indexContent() and hook_linkParse(&$pObj) in class Metaseo\Metaseo\Hook\SitemapIndexHook are fine for develpment and low-traffic systems which need to work out of the box. However, both hooks seem to be performance related and might slow down the frontend.

This is not necessary most of the time, as only the first request leads to changes in the sitemap table. Succeeding requests have no effect as long as no changes occur in the content.

Therefore, it should be possible to disable the hooks in production mode. Instead, a treewalker should process all links (via scheduler). Maybe there is already some work done in that way. How's the linkvalidator extension working?

**Comment by mblaschke** [comment] 2015-03-18 21:36
Normal pages can be indexed using an indexing crawler but any virtual pages (eg. from extensions) must be configured eg. like with EXT:crawler.
This way is really painfully if you have many extensions and many possibilities and you have to update your configuration with any extension update.

The indexContent hook should be no problem but linkParse could be an issue on high traffic sites.

The advantage of this hooks are that you don't need any configuration for the whole TYPO3 installation as long your extensions are using cHashs.

**Comment by thomaszbz** [comment] 2015-03-19 01:34
I get the idea. For instance, I won't execute the garbage collection task on a regular basis.

**Comment by mblaschke** [comment] 2015-03-29 11:43
Let me try a better solution with #21

**Comment by mblaschke** [comment] 2015-03-29 13:42
Should be better now with 51ac49d2a3356e790d5b8cef664c9c6daff0e0dd

**Comment by thomaszbz** [comment] 2015-03-30 10:09
What kind of feedback do you need?

**Comment by mblaschke** [comment] 2015-03-31 08:50
If the issue is fixed with the expiration date. But i will check this issue again in the next time.
This issue must be fixed :)

**Comment by thomaszbz** [comment] 2015-03-31 08:52
I can retest the way I did in the first comment.

**Comment by thomaszbz** [comment] 2015-03-31 09:02
Test:

- check before test: sitemap (type=841132) is filled
- updated to bd807f1
- clear caches (frontend, general, system)
- run garbage collection task

Result:

- Sitemap still is filled
- Therefore, no manual clicking is necessary after running the garbage collection.
- In that sense, the issue is solved.

Limitation of the test:

- I did not check if the garbage collection still works.

**Comment by mblaschke** [comment] 2015-04-18 13:36
Thanks for testing - closing this issue now but I will watch this isse :)

**Closed by mblaschke** 2015-04-18 13:36 UTC
Labels: need: feedback
